" pepe
set guifont=Mensch:h13.0
colorscheme xoria256
set columns=176
set lines=64

let s:save_cpo = &cpo
set cpo&vim

let Tlist_Ctags_Cmd='/usr/local/bin/ctags'

"" THE BEER-WARE LICENSE" (Revision 42):
"" <josef.pospisil@laststar.eu> wrote this file. As long as you retain this notice you
"" can do whatever you want with this stuff. If we meet some day, and you think
"" this stuff is worth it, you can buy me a beer in return. 
"" Josef 'pepe' Pospisil
